// Auto-generated by generate_data_js.py  (2026-03-03)
// null 欄位 = 無 API，請對照 debug.js 說明後手動填入

const REPORT_DATE = "2026-03-03";
const REPORT_WEEK = "TEMPLATE";

// 各 series 最後抓取日期，用於顯示「已更新」提示
const dataFreshness = {
  ffr: "2026-03-03",
  cpi: "2026-03-03",
  pce: "2026-03-03",
  nfp: "2026-03-03",
  unemployment: "2026-03-03",
};

// ── 1. 利率 / 殖利率曲線 ──────────────────────────────────────────────
const yieldCurveData = {
  labels:   ["1M","3M","6M","1Y","2Y","5Y","10Y","20Y","30Y"],
  current:  [3.74, 3.67, 3.6, 3.48, 3.38, 3.51, 3.97, 4.57, 4.64],
  prevWeek: [3.72, 3.69, 3.61, 3.51, 3.48, 3.65, 4.08, 4.66, 4.72],
};

const fedFundsRate = {
  current:     3.64,  // FRED FEDFUNDS 月均有效利率
  target:      "3.50–3.75%",  // FRED DFEDTARU/DFEDTARL 目標區間
};

// ── 2. 通膨 / CPI / PCE ────────────────────────────────────────────────
const inflationData = {
  labels:  ["Aug '25", "Sep '25", "Nov '25", "Dec '25", "Jan '26"],
  cpiYoY:  [2.94, 3.02, 2.7, 2.65, 2.39],
  coreYoY: [3.11, 3.02, 2.6, 2.65, 2.51],
  pceYoY:  [2.75, 2.79, 2.72, 2.82, 2.9],
  corePce: [2.91, 2.83, 2.76, 2.83, 3.0],
};

// ── 3. 就業市場 ─────────────────────────────────────────────────────────
const employmentData = {
  labels:               ["Sep '25", "Oct '25", "Nov '25", "Dec '25", "Jan '26"],
  nfp:                  [76, -140, 41, 48, 130],
  unemployRate:         [4.3, 4.4, 4.5, 4.4, 4.3],
  avgHourlyEarningsYoY: null,  // 請手動填入
  joltsCurrent:         null,  // 請手動填入
};

// ── 4. 股市指數（無 API，請手動填入）────────────────────────────────────
const equityData = {
  indices:         [],  // 請手動填入
  spxWeeklyLabels: [],  // 請手動填入
  spxWeeklyClose:  [],  // 請手動填入
};

// ── 5. 先期指標 ─────────────────────────────────────────────────────────
const leadingIndicators = [
  { id: 1, name: "GDP QoQ SAAR", type: "景氣", prev: "4.40%", latest: "1.40%", chgPct: -68.18, date: "2025Q4", nextUpdate: "2026年3月" },
  { id: 2, name: "聯邦基金有效利率", type: "利率", prev: "3.64%", latest: "3.64%", chgPct: 0.0, date: "2026-02", nextUpdate: "FOMC 決議" },
  { id: 3, name: "PCE 年增率 YoY", type: "通膨", prev: "2.82%", latest: "2.90%", chgPct: 2.96, date: "2025-12", nextUpdate: "Monthly" },
  { id: 4, name: "核心 PCE 年增率 YoY", type: "通膨", prev: "2.83%", latest: "3.00%", chgPct: 6.05, date: "2025-12", nextUpdate: "Monthly" },
  { id: 5, name: "CPI 年增率 YoY", type: "通膨", prev: "2.65%", latest: "2.39%", chgPct: -9.88, date: "2026-01", nextUpdate: "Monthly" },
  { id: 6, name: "核心 CPI 年增率 YoY", type: "通膨", prev: "2.65%", latest: "2.51%", chgPct: -5.08, date: "2026-01", nextUpdate: "Monthly" },
  { id: 7, name: "ISM 製造業 PMI", type: "景氣", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "每月首週" },
  { id: 8, name: "VIX（CBOE 波動率指數）", type: "市場", prev: "18.63", latest: "19.86", chgPct: 6.6, date: "2026-02-27", nextUpdate: "Daily" },
  { id: 9, name: "VXN（Nasdaq 波動率指數）", type: "市場", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "Daily" },
  { id: 10, name: "OECD 美國先行指標 CLI", type: "海外", prev: "99.72", latest: "99.85", chgPct: 0.14, date: "2024-01", nextUpdate: "Monthly" },
  { id: 11, name: "OECD 商業信心指數 BCI", type: "海外", prev: "98.76", latest: "98.97", chgPct: 0.21, date: "2024-01", nextUpdate: "Monthly" },
  { id: 12, name: "美國企業利潤（十億美元）", type: "景氣", prev: "3355.90", latest: "3591.34", chgPct: 7.02, date: "2025Q3", nextUpdate: "2026年4月" },
  { id: 13, name: "非農就業 NFP MoM（千人）", type: "就業", prev: "48", latest: "130", chgPct: 170.83, date: "2026-01", nextUpdate: "Monthly" },
  { id: 14, name: "失業率", type: "就業", prev: "4.40%", latest: "4.30%", chgPct: -2.27, date: "2026-01", nextUpdate: "Monthly" },
  { id: 15, name: "ADP 就業人數變動（千人）", type: "就業", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "每月第一週" },
  { id: 16, name: "台灣出口訂單 YoY", type: "海外", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "Monthly" },
];

// ── 6. 風險指標 ─────────────────────────────────────────────────────────
const riskIndicators = [
  { id: 1, name: "美國 5年CDS (Basic Point)", type: "信用風險", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "未公布" },
  { id: 2, name: "90天以上貸款逾期未繳-全部", type: "信用風險", prev: "1.47", latest: "1.53", chgPct: 4.08, date: "2025Q4", nextUpdate: "每季" },
  { id: 3, name: "90天以上貸款逾期未繳-住宅抵押", type: "信用風險", prev: "1.78", latest: "1.78", chgPct: 0.0, date: "2025Q4", nextUpdate: "每季" },
  { id: 4, name: "90天以上貸款逾期未繳-循環型房貸", type: "信用風險", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "每季" },
  { id: 5, name: "90天以上貸款逾期未繳-車貸", type: "信用風險", prev: "2.71", latest: "2.62", chgPct: -3.32, date: "2025Q4", nextUpdate: "每季" },
  { id: 6, name: "90天以上貸款逾期未繳-信用卡", type: "信用風險", prev: "2.98", latest: "2.94", chgPct: -1.34, date: "2025Q4", nextUpdate: "每季" },
  { id: 7, name: "90天以上貸款逾期未繳-學貸", type: "信用風險", prev: "—", latest: "—", chgPct: null, date: "—", nextUpdate: "每季" },
  { id: 8, name: "美國-商銀貸款拖欠率-信用卡", type: "信用風險", prev: "2.98%", latest: "2.94%", chgPct: -1.34, date: "2025Q4", nextUpdate: "每季" },
  { id: 9, name: "美國 高收益公司債有效殖利率（BB級）", type: "風險報酬", prev: "5.43%", latest: "5.48%", chgPct: 0.92, date: "2026-02-28", nextUpdate: "Daily" },
  { id: 10, name: "美國 高收益公司債有效殖利率（B級）", type: "風險報酬", prev: "6.85%", latest: "6.97%", chgPct: 1.75, date: "2026-02-28", nextUpdate: "Daily" },
  { id: 11, name: "美國 高收益公司債有效殖利率（CCC級或以下）", type: "風險報酬", prev: "12.93%", latest: "13.00%", chgPct: 0.54, date: "2026-02-28", nextUpdate: "Daily" },
  { id: 12, name: "SLOOS 中大型企業貸款淨需求比例", type: "景氣訊號", prev: "11.50%", latest: "16.10%", chgPct: 40.0, date: "2026Q1", nextUpdate: "每季" },
  { id: 13, name: "SLOOS 國內銀行緊縮中大型企業貸款標準淨比例", type: "景氣訊號", prev: "6.50%", latest: "5.30%", chgPct: -18.46, date: "2026Q1", nextUpdate: "每季" },
  { id: 14, name: "SLOOS 小型企業貸款淨需求比例", type: "景氣訊號", prev: "-1.70%", latest: "0.00%", chgPct: 100.0, date: "2026Q1", nextUpdate: "每季" },
  { id: 15, name: "SLOOS 國內銀行緊縮小型企業貸款標準淨比例", type: "景氣訊號", prev: "8.30%", latest: "8.90%", chgPct: 7.23, date: "2026Q1", nextUpdate: "每季" },
];

// ── News（請手動填入）────────────────────────────────────────────────────
const newsItems = [
  // { date: "YYYY-MM-DD", headline: "標題", summary: "彙整" },
];