#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["yfinance", "requests", "pyyaml", "python-dotenv", "pandas"]
# ///
"""
Stock Weekly — Fetch Script
============================
用法:
  python3 fetch.py NVDA            # 寫入 dev/NVDA-當週/data.js
  python3 fetch.py NVDA 2026-W10   # 指定資料夾
  python3 fetch.py                 # 依 config.yaml watchlist 跑全部

環境變數（填於 .env）:
  FINMIND_API_KEY   台股籌碼（FinMind）
  FINTEL_API_KEY    美股籌碼（Fintel）

資料寫出:
  dev/{TICKER}-{WEEK}/data.js
"""

import json
import os
import sys
from datetime import date
from pathlib import Path

import yaml
from dotenv import load_dotenv

from fetchers import YFinanceFetcher, FinMindFetcher, FintelFetcher, NewsFetcher
from analyzers import TechnicalAnalyzer, ChipsAnalyzer

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE = Path(__file__).parent
load_dotenv(BASE / ".env")

FINMIND_KEY = os.getenv("FINMIND_API_KEY", "")
FINTEL_KEY  = os.getenv("FINTEL_API_KEY", "")


# ── Helpers ───────────────────────────────────────────────────────────────────

def current_week() -> str:
    d = date.today()
    year, week, _ = d.isocalendar()
    return f"{year}-W{week:02d}"


def load_config() -> dict:
    with open(BASE / "config.yaml", "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def weekly_sparkline(df) -> tuple[list, list]:
    """從日線 DataFrame 取近5週收盤（每週最後一個交易日）"""
    close = df["Close"].copy()
    # 確保 index 為 DatetimeIndex（去 tz）
    if hasattr(close.index, "tz") and close.index.tz is not None:
        close.index = close.index.tz_localize(None)
    weekly = close.resample("W").last().dropna().tail(5)
    labels = [dt.strftime("%b %d") for dt in weekly.index]
    closes = [round(float(v), 2) for v in weekly.values]
    return labels, closes


def js_value(v):
    """將 Python 值轉為 JS literal（null 對應 None）"""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    # numpy scalars → plain Python number
    try:
        import numpy as np
        if isinstance(v, (np.integer,)):
            v = int(v)
        elif isinstance(v, (np.floating,)):
            v = float(v)
    except ImportError:
        pass
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, list):
        return "[" + ", ".join(js_value(x) for x in v) + "]"
    if isinstance(v, dict):
        inner = ", ".join(f"{k}: {js_value(vv)}" for k, vv in v.items())
        return "{ " + inner + " }"
    return repr(v)


def write_data_js(dest: Path, payload: dict) -> None:
    """將 payload 寫入 dest/data.js"""
    td     = payload["technical"]
    chips  = payload["chips"]
    news   = payload["news"]
    ticker = payload["ticker"]
    company = payload["company"]
    week   = payload["week"]
    market = payload["market"]
    report_date = payload["report_date"]

    lines = [
        "// Auto-generated by fetch.py — do not edit manually",
        "// ============================================================",
        "",
        f'const REPORT_DATE    = "{report_date}";',
        f'const REPORT_WEEK    = "{week}";',
        f'const REPORT_TICKER  = "{ticker}";',
        f'const REPORT_COMPANY = "{company}";',
        f'const REPORT_MARKET  = "{market}";   // "tw" | "us"',
        "",
        "// ------------------------------------------------------------",
        "// 1. 技術面",
        "// ------------------------------------------------------------",
        "const technicalData = {",
        f"  close: {js_value(td.get('close'))},",
        f"  weekChangePct: {js_value(td.get('week_change_pct'))},",
        f"  volume: {js_value(td.get('volume'))},",
        f'  date: "{td.get("date", "")}",',
        f"  ma: {{",
        f"    MA5:  {js_value(td.get('MA5'))},",
        f"    MA20: {js_value(td.get('MA20'))},",
        f"    MA60: {js_value(td.get('MA60'))},",
        f"  }},",
        f"  macd: {{",
        f"    macd:   {js_value(td.get('MACD', {}).get('macd'))},",
        f"    signal: {js_value(td.get('MACD', {}).get('signal'))},",
        f"    hist:   {js_value(td.get('MACD', {}).get('hist'))},",
        f"  }},",
        f"  bollinger: {{",
        f"    upper: {js_value(td.get('Bollinger', {}).get('upper'))},",
        f"    mid:   {js_value(td.get('Bollinger', {}).get('mid'))},",
        f"    lower: {js_value(td.get('Bollinger', {}).get('lower'))},",
        f"  }},",
        f"  weeklyLabels: {js_value(td.get('weeklyLabels', []))},",
        f"  weeklyClose:  {js_value(td.get('weeklyClose', []))},",
        "};",
        "",
        "// ------------------------------------------------------------",
        "// 2. 籌碼面",
        "// ------------------------------------------------------------",
    ]

    # Build chipsData
    inst   = chips.get("institutional", {}) or {}
    margin = chips.get("margin", {}) or {}
    si     = chips.get("short_interest") if market == "us" else None
    iown   = chips.get("institutional_ownership") if market == "us" else None

    lines += [
        "const chipsData = {",
        f'  market: "{market}",',
        "  tw: {",
        "    institutional: {",
        f'      date: "{inst.get("date", "")}",',
        f"      foreign_net:   {js_value(inst.get('foreign_net'))},",
        f"      trust_net:     {js_value(inst.get('trust_net'))},",
        f"      dealer_net:    {js_value(inst.get('dealer_net'))},",
        f"      foreign_5d_net:{js_value(inst.get('foreign_5d_net'))},",
        "    },",
        "    margin: {",
        f'      date: "{margin.get("date", "")}",',
        f"      margin_balance: {js_value(margin.get('margin_balance'))},",
        f"      short_balance:  {js_value(margin.get('short_balance'))},",
        f"      margin_change:  {js_value(margin.get('margin_change'))},",
        f"      short_change:   {js_value(margin.get('short_change'))},",
        "    },",
        "  },",
        "  us: {",
        f"    shortInterest:          {js_value(si)},",
        f"    institutionalOwnership: {js_value(iown)},",
        "  },",
        "};",
        "",
        "// ------------------------------------------------------------",
        "// 3. 消息面",
        "// ------------------------------------------------------------",
    ]

    # Build newsItems
    lines.append("const newsItems = [")
    for n in news:
        pub = n.get("publishTime", "")
        d_str = pub[:10] if pub else ""
        title = (n.get("title", "") or "").replace('"', '\\"')
        link  = (n.get("link", "") or "").replace('"', '\\"')
        lines.append(
            f'  {{ date: "{d_str}", headline: "{title}", link: "{link}" }},'
        )
    lines.append("];")

    js_text = "\n".join(lines) + "\n"
    (dest / "data.js").write_text(js_text, encoding="utf-8")
    print(f"  → {dest / 'data.js'} 寫入完成")


# ── Main fetch logic ──────────────────────────────────────────────────────────

def fetch_and_write(ticker: str, market: str, week: str, config: dict) -> None:
    dest = BASE / "dev" / f"{ticker.upper()}-{week}"
    if not dest.exists():
        print(f"[{ticker}] 目錄不存在：{dest}")
        print(f"  請先執行：python3 new_report.py {ticker} {week}")
        return

    tech_cfg = config.get("technical", {})

    news_fetcher = NewsFetcher(market=market)
    tech_analyzer = TechnicalAnalyzer(tech_cfg)
    chips_analyzer = ChipsAnalyzer()

    # ── 價格資料 ──────────────────────────────────────────────
    print(f"[{ticker}] 取得價格資料...")
    yf_fetcher = YFinanceFetcher(market=market)
    price_data = yf_fetcher.get_price_history(ticker, days=90)

    df = price_data["df"]
    company_name = price_data["longName"]

    if df.empty:
        print(f"[{ticker}] 警告：無法取得價格資料")
        tech = {}
    else:
        tech = tech_analyzer.analyze(df)
        labels, closes = weekly_sparkline(df)
        tech["weeklyLabels"] = labels
        tech["weeklyClose"]  = closes

    # ── 籌碼面 ────────────────────────────────────────────────
    chips = {}
    if market == "tw":
        if FINMIND_KEY:
            print(f"[{ticker}] 取得台股籌碼資料...")
            fm = FinMindFetcher(api_key=FINMIND_KEY)
            try:
                institutional = fm.get_institutional(ticker, days=30)
                margin        = fm.get_margin(ticker, days=30)
                chips = chips_analyzer.analyze_tw(institutional, margin)
            except Exception as e:
                print(f"[{ticker}] FinMind 資料取得失敗：{e}")
        else:
            print(f"[{ticker}] 未設定 FINMIND_API_KEY，跳過籌碼面")
    else:
        if FINTEL_KEY:
            print(f"[{ticker}] 取得美股籌碼資料...")
            ft = FintelFetcher(api_key=FINTEL_KEY)
            try:
                si   = ft.get_short_interest(ticker)
                iown = ft.get_institutional_ownership(ticker)
                chips = chips_analyzer.analyze_us(si, iown)
            except Exception as e:
                print(f"[{ticker}] Fintel 資料取得失敗：{e}")
        else:
            print(f"[{ticker}] 未設定 FINTEL_API_KEY，跳過籌碼面")

    # ── 新聞 ──────────────────────────────────────────────────
    print(f"[{ticker}] 取得近期新聞...")
    try:
        news = news_fetcher.get_news(ticker, max_items=8)
    except Exception as e:
        print(f"[{ticker}] 新聞取得失敗：{e}")
        news = []

    # ── 寫入 data.js ──────────────────────────────────────────
    write_data_js(dest, {
        "ticker":      ticker.upper(),
        "company":     company_name,
        "week":        week,
        "market":      market,
        "report_date": str(date.today()),
        "technical":   tech,
        "chips":       chips,
        "news":        news,
    })

    print(f"✅ [{ticker}] 完成")


def main():
    config    = load_config()
    watchlist = config.get("watchlist", {})
    tw_list   = [t.upper() for t in watchlist.get("tw", [])]
    us_list   = [t.upper() for t in watchlist.get("us", [])]

    if len(sys.argv) >= 2:
        ticker = sys.argv[1].upper()
        week   = sys.argv[2] if len(sys.argv) >= 3 else current_week()

        # Determine market from watchlist, fallback to heuristic
        if ticker in tw_list:
            market = "tw"
        elif ticker in us_list:
            market = "us"
        else:
            market = "tw" if ticker.isdigit() else "us"

        print(f"\n{'='*50}")
        print(f"Fetching {ticker} ({market.upper()}) — {week}")
        print("=" * 50)
        fetch_and_write(ticker, market, week, config)

    else:
        week = current_week()
        targets = (
            [(t, "tw") for t in tw_list]
            + [(t, "us") for t in us_list]
        )
        for ticker, market in targets:
            print(f"\n{'='*50}")
            print(f"Fetching {ticker} ({market.upper()}) — {week}")
            print("=" * 50)
            fetch_and_write(ticker, market, week, config)


if __name__ == "__main__":
    main()
